name: Auto Sync Fork

on:
  schedule:
    - cron: '0 */3 * * *' # 每 3 小时执行一次
  workflow_dispatch:     # 允许你手动点击测试

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4

      - name: Sync Upstream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # 告诉 GitHub 官方工具：强行用原作者的主分支更新我的当前分支
          gh repo sync sssysy/NTEUID -b main
